from flask import Flask, request
from markupsafe import escape
import bbo

app = Flask(__name__)

@app.route('/')
def hello_world():
    return "<h2>Sort By Booking Origin API</h2> <p>The server only support \"POST\" method<p> <p>Request object need csv file containing Market Feeder Report generated by RoomKeyPMS"

@app.route('/', methods=["POST"])
def SortByBookingOrigin():
    file = request.files['file']
    results = bbo.SortByBookingOrigin(file)
    return f"Booking Breakdown By Origin Result: {escape(results)}"